#开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://localhost:3306/shop
    username: root
    password: qwer1234
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  config: classpath:log4j2_dev.xml
